version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34
    container_name: prisma-db-1
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        managementApiSecret: mysecret
        databases:
          default:
            connector: postgres
            host: host.docker.internal
            database: mydb1
            schema: public
            user: postgres
            password: admin
            ssl: false
            rawAccess: true
            port: '5433'
            migrations: true
