module.exports = {
  ROLES: {
    ADMIN: "ADMIN",
    STAFF: "STAFF",
    SIMPLE: "SIMPLE"
  },
  TOKEN_TYPES: {
    ACCOUNT_ACTIVATION: "ACCOUNT_ACTIVATION",
    RESET_PASSWORD: "RESET_PASSWORD"
  }
};
